services:

  db:
    image: postgres:15-alpine
    container_name: foodgram-db
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: foodgram-backend
    env_file:
      - ../.env
    depends_on:
      - db
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../backend:/app
      - ../backend/static:/var/html/static
      - ../backend/media:/var/html/media
    expose:
      - "8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: foodgram-front
    volumes:
      - ../frontend/build:/usr/share/nginx/html/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../backend/static:/var/html/static
      - ../backend/media:/var/html/media

volumes:
  postgres_data:
